travis:
  secure:
    BINSTAR_TOKEN: Rk12eN23uSqTf+Vp90FApOeSE1GrA6uBP+HpADT0ukENYFGVrFjOIvx+g81Qo6sZZ3IqbTuNfMy7atgGO1YJkA+/MkOGewkiZZqAL7ecnjgGIhm7vcYBX4NqcllE8wDHWx52pQbr8sPhb5W+AWMy1JquYeV843j+OAmSGfa2U1b5gGYFVJjjEVHfVM05tVrf6OVEsawGuyM+AlMYxi+gQ5hs/Y3Oc9qQwjXDwZ58uV4kjaBXm8XX7KLMco/SQz++U5dvwC/G+PxcvRxCp/9MY7j2ysTg5a4FdunKX/MeUTjCCqbIPYTfwjqxq/3m+dugTDnPF7DlhYV/h6Re3gFR0CxbepWewKaMlXM5n+9wXv8HkTxmU4RBuAEq/ewvnf89BMOORnjFOWykcTgqOOfcizishdy+TUcbLtuaLyGefAMUqm3LGYljWDkvKRw4Y15o9KPO1n8suJ/BydDTxURk3lI1/sajtEzCYCoB24/9q7tt97jWJSRyx6uCVVHa/12CpWVCLVtUTaB0uAtY6d+bxtS6NR52e7XC8DxywRTVushRY6t1WGzLknaZg4qnC+8hiAftjPBqclHwHFXzvH876Wk0N6sDFsGw2wKuGRrRhw/9/jO2cXQh9NC47Oq7b9Q+iKJMKkHlujCUs3Vgn/RfXXhHVk+Eup+dONxeGLnYbMk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
